### PR TITLE
move to pyproject.toml

### PR DESCRIPTION
**Pull request by rubenpeters91**
Moved to pyproject.toml and removed old Azure pipelines

### CODE REVIEW

**Comment by sbuergers** [comment]
@rubenpeters91 nice, looks good. I am not entirely sure about deleting all the old pipelines from azure without adding new ones for github. Do we only want to keep the tests?

**Review by sbuergers — CHANGES_REQUESTED** [review]
Hmm, you cannot install with `pip install -e .` having only a `pyproject.toml` file. Should we support both `setup.py` and `pyproject.toml` for now? Otherwise, we could try to find a workaround for installing in editable mode with `pyproject.toml` only.

**Comment by rubenpeters91** [comment]
> Hmm, you cannot install with `pip install -e .` having only a `pyproject.toml` file. Should we support both `setup.py` and `pyproject.toml` for now? Otherwise, we could try to find a workaround for installing in editable mode with `pyproject.toml` only (see https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml)
> 
> ```
> (venv) steburg@L17503:~/projects/sam$ pip install -e .
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/steburg/projects/sam
> (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
> ```

Have you tried updating pip? Because I can install in editable mode...

**Comment by sbuergers** [comment]
Indeed!

**Review by sbuergers — APPROVED** [review]

**Review by abontsema — APPROVED** [review]
Very nice!

**Pull request merged**
